// <auto-generated />
using System;
using EchoesServer.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EchoesServer.Api.Migrations
{
    [DbContext(typeof(SchoolContext))]
    [Migration("20181201234046_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EchoesServer.Api.Data.Entities.Assignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<int?>("SchoolClassId");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.HasIndex("SchoolClassId");

                    b.ToTable("Assignments");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Assignment");
                });

            modelBuilder.Entity("EchoesServer.Api.Data.Entities.SchoolClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("SchoolClasses");
                });

            modelBuilder.Entity("EchoesServer.Api.Data.Entities.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<int?>("SchoolClassId");

                    b.HasKey("Id");

                    b.HasIndex("SchoolClassId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("EchoesServer.Api.Data.Entities.Exam", b =>
                {
                    b.HasBaseType("EchoesServer.Api.Data.Entities.Assignment");


                    b.ToTable("Exam");

                    b.HasDiscriminator().HasValue("Exam");
                });

            modelBuilder.Entity("EchoesServer.Api.Data.Entities.Homework", b =>
                {
                    b.HasBaseType("EchoesServer.Api.Data.Entities.Assignment");


                    b.ToTable("Homework");

                    b.HasDiscriminator().HasValue("Homework");
                });

            modelBuilder.Entity("EchoesServer.Api.Data.Entities.Assignment", b =>
                {
                    b.HasOne("EchoesServer.Api.Data.Entities.SchoolClass")
                        .WithMany("Assignments")
                        .HasForeignKey("SchoolClassId");
                });

            modelBuilder.Entity("EchoesServer.Api.Data.Entities.Student", b =>
                {
                    b.HasOne("EchoesServer.Api.Data.Entities.SchoolClass", "SchoolClass")
                        .WithMany("Students")
                        .HasForeignKey("SchoolClassId");
                });
#pragma warning restore 612, 618
        }
    }
}
